name: CI / CD 연습

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # PostgreSQL Service 설정
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: test
        options: --health-cmd="pg_isready -U test" --health-timeout=5s --health-start-period=10s --health-retries=5

      # MongoDB Service 설정
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: 1234
          MONGO_INITDB_DATABASE: test
        options: --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'" --health-timeout=5s --health-start-period=10s --health-retries=5

      # Redis Service 설정
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        volumes:
          - redis_data:/data
          - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf  # 경로 확인
        options:
          --health-cmd="redis-cli ping"  # Redis 서버 준비 상태 확인 명령어 추가
          --health-timeout=5s
          --health-start-period=10s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 소스 코드 체크아웃

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 설치
        uses: gradle/actions/setup-gradle@v4

      - name: 빌드 시작
        run: ./gradlew build

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-test .

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-test

